name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  CI:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: CI
      shell: pwsh
      run: |
        .\xweb.ps1 install
        .\xweb.ps1 stop mysql